import Link from "next/link";
import { PolicyLayout, PolicySection } from "../_components";

export const metadata = { title: "Terms & Conditions", description: "Buzzora terms and conditions." };

export default function TermsAndConditionsPage() {
  return (
    <PolicyLayout title="Terms & Conditions" intro="The terms governing access to and orders placed through Buzzora.co.in.">
      <PolicySection title="Business Identity & Legal Terms">
        <p>This document is an electronic record generated by a computer system under the Information Technology Act, 2000 and applicable rules, and does not require any physical or digital signatures.</p>
        <p>This website Buzzora.co.in (Platform) is owned and operated by <strong>Kannu Priya</strong>, a sole proprietorship operating under the trade/brand name <strong>Buzzora</strong>, with its principal place of business at Near Govt Middle School, Janglote Kathua Tehsil, Kathua, Kathua, Jammu &amp; Kashmir - 184104 (referred to as &quot;Platform Owner&quot;, &quot;Buzzora&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;).</p>
        <p>By accessing, browsing, or placing an order through the Platform, you agree to be bound by these Terms &amp; Conditions and our policies, including our <Link href="/policies/privacy-policy" className="underline text-honey-700 font-semibold">Privacy Policy</Link>, <Link href="/policies/refund-cancellation" className="underline text-honey-700 font-semibold">Refund &amp; Cancellation Policy</Link>, <Link href="/policies/return-policy" className="underline text-honey-700 font-semibold">Return Policy</Link>, and <Link href="/policies/shipping-policy" className="underline text-honey-700 font-semibold">Shipping Policy</Link>. Please read them carefully before proceeding.</p>
      </PolicySection>

      <PolicySection title="Products & Descriptions">
        <p>Buzzora offers raw honey products through the Platform. Product names, descriptions, images, weights/quantities, and prices are displayed on the website.</p>
        <p>Product availability is subject to change without prior notice. Product images are intended to accurately represent our products; however, as raw honey is a natural agricultural product, slight natural variations in colour, texture, or natural crystallization may occur between harvests.</p>
        <p>Product information provided on the website is factual and educational. We do not make therapeutic, medical, or guaranteed health claims regarding our food products.</p>
      </PolicySection>

      <PolicySection title="Pricing">
        <p>Product prices are displayed on the Platform in Indian Rupees (₹). Prices are subject to change prior to order placement. The price applicable to your order is the price clearly shown at the time of checkout.</p>
        <p>Any applicable shipping charges will be clearly communicated during checkout or during order confirmation prior to dispatch.</p>
      </PolicySection>

      <PolicySection title="Order Process & Confirmation">
        <p>To place an order on Buzzora, customers select products, add them to the shopping cart, provide accurate shipping and contact information, and submit the order. Customer account creation or registration is not required to complete a purchase.</p>
        <p>Orders are subject to availability and verification. Buzzora may contact customers via phone, email, or messaging apps if clarification is required regarding delivery details or order fulfillment.</p>
      </PolicySection>

      <PolicySection title="Payment Terms">
        <p>Payments may be processed through third-party payment service providers made available through the website or manual payment confirmation. Payment credentials are handled by the applicable payment provider in accordance with its own security practices and terms. Buzzora does not directly store customers&apos; complete payment card details on its servers.</p>
      </PolicySection>

      <PolicySection title="Shipping & Delivery">
        <p>Orders placed on the Platform are shipped and delivered in accordance with our <Link href="/policies/shipping-policy" className="underline text-honey-700 font-semibold">Shipping Policy</Link>.</p>
      </PolicySection>

      <PolicySection title="Cancellation, Returns & Refunds">
        <p>Order cancellations, returns, exchanges, and refunds are governed by our <Link href="/policies/refund-cancellation" className="underline text-honey-700 font-semibold">Refund &amp; Cancellation Policy</Link> and <Link href="/policies/return-policy" className="underline text-honey-700 font-semibold">Return Policy</Link>.</p>
      </PolicySection>

      <PolicySection title="Customer Responsibilities">
        <p>Customers using the Platform agree to:</p>
        <ul className="list-disc pl-5 space-y-1.5 text-charcoal-mute">
          <li>Provide true, accurate, and complete shipping address and contact details.</li>
          <li>Review order details carefully prior to submitting an order.</li>
          <li>Use the Platform and its services only for lawful purposes in compliance with Indian laws.</li>
        </ul>
      </PolicySection>

      <PolicySection title="Website Content & Intellectual Property">
        <p>All content on the Platform — including the Buzzora brand name, logo, original text, images, product graphics, and website design — is proprietary to Buzzora and protected under applicable copyright and intellectual property laws. Content may not be copied, reproduced, or used without prior written authorization.</p>
      </PolicySection>

      <PolicySection title="Website Availability & Limitation of Liability">
        <p>Buzzora strives to keep the website functional and accessible. However, access may occasionally be interrupted for scheduled maintenance, technical updates, or third-party service outages. Buzzora shall not be liable for indirect or consequential damages arising from website interruptions or courier delays beyond reasonable control.</p>
      </PolicySection>

      <PolicySection title="Governing Law & Jurisdiction">
        <p>These Terms &amp; Conditions and any disputes relating to orders placed on Buzzora shall be governed by and construed in accordance with the laws of India. All disputes shall be subject to the exclusive jurisdiction of the courts in Kathua, Jammu &amp; Kashmir, India.</p>
      </PolicySection>

      <PolicySection title="Contact Information">
        <p>For any questions or concerns regarding these Terms &amp; Conditions, please contact us:</p>
        <ul className="mt-2 space-y-1 text-sm text-charcoal-mute">
          <li><strong>Trade / Brand Name:</strong> Buzzora</li>
          <li><strong>Legal Proprietor:</strong> Kannu Priya (Sole Proprietorship)</li>
          <li><strong>Registered Business Address:</strong> Near Govt Middle School, Janglote Kathua Tehsil, Kathua, Kathua, Jammu &amp; Kashmir - 184104</li>
          <li><strong>Business Email:</strong> <a href="mailto:buzzora.dev@gmail.com" className="underline text-honey-700">buzzora.dev@gmail.com</a></li>
          <li><strong>Business Phone:</strong> <a href="https://wa.me/919186009531" target="_blank" rel="noopener noreferrer" className="underline text-honey-700">+91 9186009531</a></li>
          <li><strong>Contact Form:</strong> <Link href="/contact" className="underline text-honey-700">Contact Us Page</Link></li>
        </ul>
      </PolicySection>
    </PolicyLayout>
  );
}
