import { Numbered, PolicyLayout, PolicySection } from "../_components";

export const metadata = { title: "Terms & Conditions", description: "Buzzora terms and conditions." };

export default function TermsAndConditionsPage() {
  return (
    <PolicyLayout title="Terms & Conditions" intro="The terms governing access to Buzzora.co.in, the Platform, and its services.">
      <PolicySection>
        <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
        <p>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name Buzzora.co.in (Website), including the related mobile site and mobile application (Platform).</p>
        <p>The Platform is owned by 9186009531, a company incorporated under the Companies Act, 1956 with its registered office at Janglote, Kathua (Platform Owner, we, us, our).</p>
        <p>Your use of the Platform and services and tools are governed by these Terms of Use and the applicable policies incorporated by reference. By using the Platform, you contract with the Platform Owner and agree that these terms and policies constitute your binding obligations.</p>
        <p>These Terms of Use may be modified at any time. It is your responsibility to periodically review them. Wherever the context requires, you, your, or user means any natural or legal person who has agreed to become a user or buyer on the Platform.</p>
        <p>ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE. PLEASE READ THEM CAREFULLY BEFORE PROCEEDING.</p>
      </PolicySection>
      <PolicySection title="Use of the Platform">
        <Numbered>
          <li>To access and use the Services, you agree to provide true, accurate and complete information during and after registration, and you are responsible for all acts done through your registered account.</li>
          <li>Neither we nor third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on the website or through the Services.</li>
          <li>Your use of the Services and Platform is entirely at your own risk and discretion. You are required to independently assess that the Services meet your requirements.</li>
          <li>The contents of the Platform and Services are proprietary to us or licensed to us. You have no authority to claim intellectual property rights, title, or interest in the contents, including its design, layout, look, and graphics.</li>
          <li>Unauthorized use of the Platform or Services may lead to action under these Terms of Use or applicable laws.</li>
          <li>You agree to pay the charges associated with availing the Services.</li>
          <li>You agree not to use the Platform or Services for any unlawful, illegal, or forbidden purpose, or in violation of Indian or local laws.</li>
          <li>The website and Services may contain links to third-party websites. Those websites are governed by their own terms and policies.</li>
          <li>When you initiate a transaction, you enter into a legally binding and enforceable contract with the Platform Owner for the Services.</li>
          <li>You shall indemnify and hold harmless the Platform Owner, its affiliates, group companies, officers, directors, agents, and employees from claims, demands, actions, or penalties arising from your breach of these Terms or violation of law or third-party rights.</li>
          <li>The parties shall not be liable for failure to perform an obligation when performance is prevented or delayed by a force majeure event.</li>
          <li>These Terms and any dispute relating to them shall be governed by and construed in accordance with the laws of India.</li>
          <li>All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in and.</li>
          <li>Concerns or communications relating to these Terms must be communicated using the contact information provided on this website.</li>
        </Numbered>
      </PolicySection>
    </PolicyLayout>
  );
}
